export class BoxesModel{

	box_type:number;
	box_steps:any[];
    box_status:number;
    box_size:number;
    box_price:number;
    box_price_small:number;
    box_price_regular:number;
    box_color_small:string;
    box_color_regular:string;
    box_size_small:number;
    box_size_regular:number;
    box_dimensions_small:number;
    box_dimensions_regular:number;
    box_deliver_to:string;
    box_deliver_from:string;
    box_deliver_message:string;
    box_deliver_checkbox:boolean;
    box_id:string;
    box_img:string;
    box_name:string;
    box_arts:any[];
    box_arts_ids:any[];
    box_arts_cant:any[];
    box_subtotal:string;
    box_type_small:string;
    box_type_regular:string;
}